# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Po7KN5thpvlOiCfn8IMPdJsYclwqytOs
"""

import array

# ---------------- Integers ----------------
# Sample inventory stock quantities
stock_quantities = [15, 30, 45, 10, 50, 25]

total = sum(stock_quantities)
average = total / len(stock_quantities)
minimum = min(stock_quantities)
maximum = max(stock_quantities)

print("=== Inventory Stock Monitor ===")
print(f"Quantities: {stock_quantities}")
print(f"Total Stock: {total}, Average Stock: {average:.2f}, Min: {minimum}, Max: {maximum}\n")

# ---------------- Strings with f-strings ----------------
report = (
    f"Inventory Report:\n"
    f"-> Total items in stock: {total}\n"
    f"-> Average stock per item: {average:.2f}\n"
)
print(report)

# ---------------- Booleans ----------------
threshold = 25
if (average > threshold) and (maximum > threshold):  # compound condition
    print("Status: Above Standard ✅")
else:
    print("Status: Below Standard ⚠")
print()

# ---------------- Lists ----------------
items = ["Apples", "Bananas", "Oranges", "Mangoes"]
print("Original Items List:", items)

# Add a new element
items.append("Grapes")
# Remove one based on a condition (remove 'Bananas' if exists)
if "Bananas" in items:
    items.remove("Bananas")

# Sort list
items.sort()
print("Modified & Sorted Items List:", items, "\n")

# ---------------- Arrays ----------------
# Store a fixed-size numeric subset
arr = array.array('i', [15, 30, 45])  # integers only
arr_sum = sum(arr)
list_sum = sum(stock_quantities)

print("Array contents:", arr)
print("Array sum:", arr_sum)
print("List sum:", list_sum)
print(f"Array sum is {'equal to' if arr_sum == list_sum else 'different from'} List sum\n")

# ---------------- Dictionaries ----------------
inventory_records = [
    {"id": 1, "name": "Apples", "value": 15},
    {"id": 2, "name": "Oranges", "value": 30},
    {"id": 3, "name": "Mangoes", "value": 45},
]

print("Original Records:", inventory_records)

# Update one record (change Oranges value)
for record in inventory_records:
    if record["id"] == 2:
        record["value"] = 35

# Delete another (remove Mangoes)
inventory_records = [r for r in inventory_records if r["id"] != 3]

# Compute total of 'value' field
total_value = sum(r["value"] for r in inventory_records)

print("Updated Records:", inventory_records)
print("Total value across all records:", total_value)