# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RSp8Xm7RxOE-fo7DTLp-kbxXwCqmOQim
"""

# Stack for Irembo steps
irembo_stack = []

# Push steps
irembo_stack.append("Step1: Fill Name")
irembo_stack.append("Step2: Fill Address")
irembo_stack.append("Step3: Confirm")

# Undo last step (pop)
irembo_stack.pop()

# Current step (top of stack)
current_step = irembo_stack[-1] if irembo_stack else "No steps"
print(current_step)

# Stack for UR labs experiments
ur_labs_stack = []

# Push experiments
ur_labs_stack.append("Experiment1")
ur_labs_stack.append("Experiment2")
ur_labs_stack.append("Experiment3")

# Pop two experiments
ur_labs_stack.pop()
ur_labs_stack.pop()

# Remaining experiment
remaining = ur_labs_stack[-1] if ur_labs_stack else "No experiments"
print(remaining)

from collections import deque

# Queue for buses at Nyabugogo
buses = deque(["Bus1", "Bus2", "Bus3", "Bus4", "Bus5", "Bus6"])

# 3 buses depart (dequeue 3 times)
buses.popleft()
buses.popleft()
buses.popleft()

# Bus at the front
front_bus = buses[0] if buses else "No buses"
print(front_bus)

# Queue for BK ATM customers
customers = deque(["Customer1", "Customer2", "Customer3", "Customer4"])

# 1 withdrawal (dequeue once)
customers.popleft()

# Next customer in line
next_customer = customers[0] if customers else "No customers"
print(next_customer)